### ISSUE TITLE
Disable scrolling

### ISSUE THREAD

**Issue by Dule95D** [Mulham-Raee/HorizontalCalendar#3]
Hello buddy,

Great library and thank you for sharing this with us! 

How would i disable scrolling or listen for scroll when user stopped scrolling at one date, so i can fetch data from server. Otherwise if he is scrolling fast, it will not be good for performance and maybe some data will not be loaded at right date. 

Thank you in advance.
Greetz.

**Comment by Mulham-Raee** [comment]
Hi @Dule95D 

Thank you.

You can listen for scroll events withing **HorizontalCalendarListener**, you just have to override `onCalendarScroll `method, check [README](https://github.com/Mulham-Raee/HorizontalCalendar/blob/master/README.md).

But in your case `onDateSelected` will work for you as it will also be triggered once the calendar stops scrolling, not only onClick events.

What do you mean by disabling the scroll? if your problem is solved please let me know to close this issue.

**Comment by KarthikPugal86** [comment]
Hi Mulham,
 final Calendar defaultDate = Calendar.getInstance();
        defaultDate.add(Calendar.MONTH, -1);
        defaultDate.add(Calendar.DAY_OF_WEEK, +3);

horizontalCalendar.post(new Runnable() {
            @Override
            public void run() {
                Log.i("MainActivity", "defaultDate "+defaultDate.getTime());
                horizontalCalendar.selectDate(defaultDate.getTime(), true);
            }
        });

But response is two date is selected, How can i fix this problem?
Reason : int selectedItemPosition = horizontalCalendarView.getPositionOfCenterItem();
Start Data & Default Date also 1st time assigned centerPostion.

[Screen Shot](https://www.dropbox.com/s/jgzhf61ke0uh131/horizontalcalendar.jpeg?dl=0)

**Comment by sanjeet007** [comment]
i want to decibel scrolling indicator
